version: "3.8"
services:
    web:
        build: .
        restart: "no"
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www
    mysql:
        image: "mysql:latest"
        restart: "no"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: docker_skeleton
            MYSQL_USER: docker_skeleton
            MYSQL_PASSWORD: ew0jFuOwMa
            MYSQL_RANDOM_ROOT_PASSWORD: "True"
        ports:
            - "3306:3306"